//This file was generated by program.
#include "../rcp_pch.h"
#include "../rcp_utility.h"
#define RCP_INTERNAL_STRUCTURE
#include "../rcp_type.h"
#include "../rcp_json_write.h"
#include "rcp_number.h"
#include "rcp_map.h"
#include "rcp_array.h"
#include "rcp_struct.h"
#include "rcp_string.h"
#include "rcp_type_etc.h"

struct rcp_type_core rcp_null_type_def = {
	sizeof (void*),
	0,
	"null",
	NULL,
	NULL,
	NULL,
	NULL,
	rcp_null_write_json,
};

struct rcp_type_core rcp_ref_type_def = {
	sizeof (void*),
	1,
	"ref",
	rcp_ref_init,
	rcp_ref_deinit,
	rcp_ref_copy,
	NULL,
	rcp_ref_write_json,
};

struct rcp_type_core rcp_map_type_def = {
	sizeof (void*),
	16,
	"map",
	rcp_map_init,
	rcp_map_deinit,
	NULL,
	NULL,
	rcp_map_write_json,
};

struct rcp_type_core rcp_array_type_def = {
	sizeof (void*),
	18,
	"array",
	rcp_array_init,
	rcp_array_deinit,
	NULL,
	NULL,
	rcp_array_write_json,
};

struct rcp_type_core rcp_string_type_def = {
	sizeof (void*),
	20,
	"string",
	rcp_string_init,
	rcp_string_deinit,
	rcp_string_copy,
	rcp_string_compare,
	rcp_string_write_json,
};

struct rcp_type_core rcp_bool8_type_def = {
	sizeof (void*),
	25,
	"bool8",
	NULL,
	NULL,
	rcp_bool8_copy,
	NULL,
	rcp_bool8_write_json,
};

struct rcp_type_core rcp_bool32_type_def = {
	sizeof (void*),
	26,
	"bool32",
	NULL,
	NULL,
	rcp_bool32_copy,
	NULL,
	rcp_bool32_write_json,
};

struct rcp_type_core rcp_uint8_type_def = {
	sizeof (void*),
	32,
	"uint8",
	NULL,
	NULL,
	rcp_uint8_copy,
	rcp_uint8_compare,
	rcp_uint8_write_json,
};

struct rcp_type_core rcp_uint16_type_def = {
	sizeof (void*),
	33,
	"uint16",
	NULL,
	NULL,
	rcp_uint16_copy,
	rcp_uint16_compare,
	rcp_uint16_write_json,
};

struct rcp_type_core rcp_uint32_type_def = {
	sizeof (void*),
	34,
	"uint32",
	NULL,
	NULL,
	rcp_uint32_copy,
	rcp_uint32_compare,
	rcp_uint32_write_json,
};

struct rcp_type_core rcp_uint64_type_def = {
	sizeof (void*),
	35,
	"uint64",
	NULL,
	NULL,
	rcp_uint64_copy,
	rcp_uint64_compare,
	rcp_uint64_write_json,
};

struct rcp_type_core rcp_int8_type_def = {
	sizeof (void*),
	40,
	"int8",
	NULL,
	NULL,
	rcp_int8_copy,
	rcp_int8_compare,
	rcp_int8_write_json,
};

struct rcp_type_core rcp_int16_type_def = {
	sizeof (void*),
	41,
	"int16",
	NULL,
	NULL,
	rcp_int16_copy,
	rcp_int16_compare,
	rcp_int16_write_json,
};

struct rcp_type_core rcp_int32_type_def = {
	sizeof (void*),
	42,
	"int32",
	NULL,
	NULL,
	rcp_int32_copy,
	rcp_int32_compare,
	rcp_int32_write_json,
};

struct rcp_type_core rcp_int64_type_def = {
	sizeof (void*),
	43,
	"int64",
	NULL,
	NULL,
	rcp_int64_copy,
	rcp_int64_compare,
	rcp_int64_write_json,
};

struct rcp_type_core rcp_float_type_def = {
	sizeof (void*),
	49,
	"float",
	NULL,
	NULL,
	rcp_float_copy,
	rcp_float_compare,
	rcp_float_write_json,
};

struct rcp_type_core rcp_double_type_def = {
	sizeof (void*),
	50,
	"double",
	NULL,
	NULL,
	rcp_double_copy,
	rcp_double_compare,
	rcp_double_write_json,
};

struct rcp_type_core rcp_pointer_type_def = {
	sizeof (void*),
	2,
	"pointer",
	NULL,
	NULL,
	NULL,
	rcp_pointer_compare,
	NULL,
};

const rcp_type_ref rcp_null_type = &rcp_null_type_def;

const rcp_type_ref rcp_ref_type = &rcp_ref_type_def;

const rcp_type_ref rcp_map_type = &rcp_map_type_def;

const rcp_type_ref rcp_array_type = &rcp_array_type_def;

const rcp_type_ref rcp_string_type = &rcp_string_type_def;

const rcp_type_ref rcp_bool8_type = &rcp_bool8_type_def;

const rcp_type_ref rcp_bool32_type = &rcp_bool32_type_def;

const rcp_type_ref rcp_uint8_type = &rcp_uint8_type_def;

const rcp_type_ref rcp_uint16_type = &rcp_uint16_type_def;

const rcp_type_ref rcp_uint32_type = &rcp_uint32_type_def;

const rcp_type_ref rcp_uint64_type = &rcp_uint64_type_def;

const rcp_type_ref rcp_int8_type = &rcp_int8_type_def;

const rcp_type_ref rcp_int16_type = &rcp_int16_type_def;

const rcp_type_ref rcp_int32_type = &rcp_int32_type_def;

const rcp_type_ref rcp_int64_type = &rcp_int64_type_def;

const rcp_type_ref rcp_float_type = &rcp_float_type_def;

const rcp_type_ref rcp_double_type = &rcp_double_type_def;

const rcp_type_ref rcp_pointer_type = &rcp_pointer_type_def;
