//This file was generated by program.

extern struct rcp_type_core rcp_uint64_type;

extern struct rcp_type_core rcp_uint32_type;

extern struct rcp_type_core rcp_uint16_type;

extern struct rcp_type_core rcp_uint8_type;

extern struct rcp_type_core rcp_int64_type;

extern struct rcp_type_core rcp_int32_type;

extern struct rcp_type_core rcp_int16_type;

extern struct rcp_type_core rcp_int8_type;

extern struct rcp_type_core rcp_double_type;

extern struct rcp_type_core rcp_float_type;

extern struct rcp_type_core rcp_pointer_type;
