//This file was generated by program.
#include "rcp_pch.h"
#include "rcp_type.h"

void rcp_type_uint64_copy(void *src, void *dst){
	*(uint64_t*)dst = *(uint64_t*)src;
}
int rcp_type_uint64_compair(void *src, void *dst){
	//this implement cause over flow
	//return *(uint64_t*)dst - *(uint64_t*)src;
	if (*(uint64_t*)dst<*(uint64_t*)src)
		return -1;
	if (*(uint64_t*)dst>*(uint64_t*)src)
		return +1;
	return 0;
}
struct rcp_type_core rcp_type_uint64 = {
	NULL,//init
	NULL,//free
	rcp_type_uint64_copy,
	rcp_type_uint64_compair,
	sizeof(uint64_t)
};

void rcp_type_uint32_copy(void *src, void *dst){
	*(uint32_t*)dst = *(uint32_t*)src;
}
int rcp_type_uint32_compair(void *src, void *dst){
	//this implement cause over flow
	//return *(uint32_t*)dst - *(uint32_t*)src;
	if (*(uint32_t*)dst<*(uint32_t*)src)
		return -1;
	if (*(uint32_t*)dst>*(uint32_t*)src)
		return +1;
	return 0;
}
struct rcp_type_core rcp_type_uint32 = {
	NULL,//init
	NULL,//free
	rcp_type_uint32_copy,
	rcp_type_uint32_compair,
	sizeof(uint32_t)
};

void rcp_type_uint16_copy(void *src, void *dst){
	*(uint16_t*)dst = *(uint16_t*)src;
}
int rcp_type_uint16_compair(void *src, void *dst){
	//this implement cause over flow
	//return *(uint16_t*)dst - *(uint16_t*)src;
	if (*(uint16_t*)dst<*(uint16_t*)src)
		return -1;
	if (*(uint16_t*)dst>*(uint16_t*)src)
		return +1;
	return 0;
}
struct rcp_type_core rcp_type_uint16 = {
	NULL,//init
	NULL,//free
	rcp_type_uint16_copy,
	rcp_type_uint16_compair,
	sizeof(uint16_t)
};

void rcp_type_uint8_copy(void *src, void *dst){
	*(uint8_t*)dst = *(uint8_t*)src;
}
int rcp_type_uint8_compair(void *src, void *dst){
	//this implement cause over flow
	//return *(uint8_t*)dst - *(uint8_t*)src;
	if (*(uint8_t*)dst<*(uint8_t*)src)
		return -1;
	if (*(uint8_t*)dst>*(uint8_t*)src)
		return +1;
	return 0;
}
struct rcp_type_core rcp_type_uint8 = {
	NULL,//init
	NULL,//free
	rcp_type_uint8_copy,
	rcp_type_uint8_compair,
	sizeof(uint8_t)
};

void rcp_type_int64_copy(void *src, void *dst){
	*(int64_t*)dst = *(int64_t*)src;
}
int rcp_type_int64_compair(void *src, void *dst){
	//this implement cause over flow
	//return *(int64_t*)dst - *(int64_t*)src;
	if (*(int64_t*)dst<*(int64_t*)src)
		return -1;
	if (*(int64_t*)dst>*(int64_t*)src)
		return +1;
	return 0;
}
struct rcp_type_core rcp_type_int64 = {
	NULL,//init
	NULL,//free
	rcp_type_int64_copy,
	rcp_type_int64_compair,
	sizeof(int64_t)
};

void rcp_type_int32_copy(void *src, void *dst){
	*(int32_t*)dst = *(int32_t*)src;
}
int rcp_type_int32_compair(void *src, void *dst){
	//this implement cause over flow
	//return *(int32_t*)dst - *(int32_t*)src;
	if (*(int32_t*)dst<*(int32_t*)src)
		return -1;
	if (*(int32_t*)dst>*(int32_t*)src)
		return +1;
	return 0;
}
struct rcp_type_core rcp_type_int32 = {
	NULL,//init
	NULL,//free
	rcp_type_int32_copy,
	rcp_type_int32_compair,
	sizeof(int32_t)
};

void rcp_type_int16_copy(void *src, void *dst){
	*(int16_t*)dst = *(int16_t*)src;
}
int rcp_type_int16_compair(void *src, void *dst){
	//this implement cause over flow
	//return *(int16_t*)dst - *(int16_t*)src;
	if (*(int16_t*)dst<*(int16_t*)src)
		return -1;
	if (*(int16_t*)dst>*(int16_t*)src)
		return +1;
	return 0;
}
struct rcp_type_core rcp_type_int16 = {
	NULL,//init
	NULL,//free
	rcp_type_int16_copy,
	rcp_type_int16_compair,
	sizeof(int16_t)
};

void rcp_type_int8_copy(void *src, void *dst){
	*(int8_t*)dst = *(int8_t*)src;
}
int rcp_type_int8_compair(void *src, void *dst){
	//this implement cause over flow
	//return *(int8_t*)dst - *(int8_t*)src;
	if (*(int8_t*)dst<*(int8_t*)src)
		return -1;
	if (*(int8_t*)dst>*(int8_t*)src)
		return +1;
	return 0;
}
struct rcp_type_core rcp_type_int8 = {
	NULL,//init
	NULL,//free
	rcp_type_int8_copy,
	rcp_type_int8_compair,
	sizeof(int8_t)
};

void rcp_type_double_copy(void *src, void *dst){
	*(double*)dst = *(double*)src;
}
int rcp_type_double_compair(void *src, void *dst){
	//this implement cause over flow
	//return *(double*)dst - *(double*)src;
	if (*(double*)dst<*(double*)src)
		return -1;
	if (*(double*)dst>*(double*)src)
		return +1;
	return 0;
}
struct rcp_type_core rcp_type_double = {
	NULL,//init
	NULL,//free
	rcp_type_double_copy,
	rcp_type_double_compair,
	sizeof(double)
};

void rcp_type_float_copy(void *src, void *dst){
	*(float*)dst = *(float*)src;
}
int rcp_type_float_compair(void *src, void *dst){
	//this implement cause over flow
	//return *(float*)dst - *(float*)src;
	if (*(float*)dst<*(float*)src)
		return -1;
	if (*(float*)dst>*(float*)src)
		return +1;
	return 0;
}
struct rcp_type_core rcp_type_float = {
	NULL,//init
	NULL,//free
	rcp_type_float_copy,
	rcp_type_float_compair,
	sizeof(float)
};

void rcp_type_pointer_copy(void *src, void *dst){
	*(void**)dst = *(void**)src;
}
int rcp_type_pointer_compair(void *src, void *dst){
	//this implement cause over flow
	//return *(void**)dst - *(void**)src;
	if (*(void**)dst<*(void**)src)
		return -1;
	if (*(void**)dst>*(void**)src)
		return +1;
	return 0;
}
struct rcp_type_core rcp_type_pointer = {
	NULL,//init
	NULL,//free
	rcp_type_pointer_copy,
	rcp_type_pointer_compair,
	sizeof(void*)
};
