//This file was generated by program.
#include "rcp_pch.h"
#include "rcp_utility.h"
#include "rcp_type.h"

void rcp_uint64_type_copy(void *src, void *dst){
	*(uint64_t*)dst = *(uint64_t*)src;
}
int rcp_uint64_type_compair(void *src, void *dst){
	//this implement cause over flow
	//return *(uint64_t*)dst - *(uint64_t*)src;
	if (*(uint64_t*)dst<*(uint64_t*)src)
		return -1;
	if (*(uint64_t*)dst>*(uint64_t*)src)
		return +1;
	return 0;
}
struct rcp_type_core rcp_uint64_type = {
	sizeof(uint64_t),
	NULL,//init
	NULL,//free
	rcp_uint64_type_copy,
	rcp_uint64_type_compair,
};

void rcp_uint32_type_copy(void *src, void *dst){
	*(uint32_t*)dst = *(uint32_t*)src;
}
int rcp_uint32_type_compair(void *src, void *dst){
	//this implement cause over flow
	//return *(uint32_t*)dst - *(uint32_t*)src;
	if (*(uint32_t*)dst<*(uint32_t*)src)
		return -1;
	if (*(uint32_t*)dst>*(uint32_t*)src)
		return +1;
	return 0;
}
struct rcp_type_core rcp_uint32_type = {
	sizeof(uint32_t),
	NULL,//init
	NULL,//free
	rcp_uint32_type_copy,
	rcp_uint32_type_compair,
};

void rcp_uint16_type_copy(void *src, void *dst){
	*(uint16_t*)dst = *(uint16_t*)src;
}
int rcp_uint16_type_compair(void *src, void *dst){
	//this implement cause over flow
	//return *(uint16_t*)dst - *(uint16_t*)src;
	if (*(uint16_t*)dst<*(uint16_t*)src)
		return -1;
	if (*(uint16_t*)dst>*(uint16_t*)src)
		return +1;
	return 0;
}
struct rcp_type_core rcp_uint16_type = {
	sizeof(uint16_t),
	NULL,//init
	NULL,//free
	rcp_uint16_type_copy,
	rcp_uint16_type_compair,
};

void rcp_uint8_type_copy(void *src, void *dst){
	*(uint8_t*)dst = *(uint8_t*)src;
}
int rcp_uint8_type_compair(void *src, void *dst){
	//this implement cause over flow
	//return *(uint8_t*)dst - *(uint8_t*)src;
	if (*(uint8_t*)dst<*(uint8_t*)src)
		return -1;
	if (*(uint8_t*)dst>*(uint8_t*)src)
		return +1;
	return 0;
}
struct rcp_type_core rcp_uint8_type = {
	sizeof(uint8_t),
	NULL,//init
	NULL,//free
	rcp_uint8_type_copy,
	rcp_uint8_type_compair,
};

void rcp_int64_type_copy(void *src, void *dst){
	*(int64_t*)dst = *(int64_t*)src;
}
int rcp_int64_type_compair(void *src, void *dst){
	//this implement cause over flow
	//return *(int64_t*)dst - *(int64_t*)src;
	if (*(int64_t*)dst<*(int64_t*)src)
		return -1;
	if (*(int64_t*)dst>*(int64_t*)src)
		return +1;
	return 0;
}
struct rcp_type_core rcp_int64_type = {
	sizeof(int64_t),
	NULL,//init
	NULL,//free
	rcp_int64_type_copy,
	rcp_int64_type_compair,
};

void rcp_int32_type_copy(void *src, void *dst){
	*(int32_t*)dst = *(int32_t*)src;
}
int rcp_int32_type_compair(void *src, void *dst){
	//this implement cause over flow
	//return *(int32_t*)dst - *(int32_t*)src;
	if (*(int32_t*)dst<*(int32_t*)src)
		return -1;
	if (*(int32_t*)dst>*(int32_t*)src)
		return +1;
	return 0;
}
struct rcp_type_core rcp_int32_type = {
	sizeof(int32_t),
	NULL,//init
	NULL,//free
	rcp_int32_type_copy,
	rcp_int32_type_compair,
};

void rcp_int16_type_copy(void *src, void *dst){
	*(int16_t*)dst = *(int16_t*)src;
}
int rcp_int16_type_compair(void *src, void *dst){
	//this implement cause over flow
	//return *(int16_t*)dst - *(int16_t*)src;
	if (*(int16_t*)dst<*(int16_t*)src)
		return -1;
	if (*(int16_t*)dst>*(int16_t*)src)
		return +1;
	return 0;
}
struct rcp_type_core rcp_int16_type = {
	sizeof(int16_t),
	NULL,//init
	NULL,//free
	rcp_int16_type_copy,
	rcp_int16_type_compair,
};

void rcp_int8_type_copy(void *src, void *dst){
	*(int8_t*)dst = *(int8_t*)src;
}
int rcp_int8_type_compair(void *src, void *dst){
	//this implement cause over flow
	//return *(int8_t*)dst - *(int8_t*)src;
	if (*(int8_t*)dst<*(int8_t*)src)
		return -1;
	if (*(int8_t*)dst>*(int8_t*)src)
		return +1;
	return 0;
}
struct rcp_type_core rcp_int8_type = {
	sizeof(int8_t),
	NULL,//init
	NULL,//free
	rcp_int8_type_copy,
	rcp_int8_type_compair,
};

void rcp_double_type_copy(void *src, void *dst){
	*(double*)dst = *(double*)src;
}
int rcp_double_type_compair(void *src, void *dst){
	//this implement cause over flow
	//return *(double*)dst - *(double*)src;
	if (*(double*)dst<*(double*)src)
		return -1;
	if (*(double*)dst>*(double*)src)
		return +1;
	return 0;
}
struct rcp_type_core rcp_double_type = {
	sizeof(double),
	NULL,//init
	NULL,//free
	rcp_double_type_copy,
	rcp_double_type_compair,
};

void rcp_float_type_copy(void *src, void *dst){
	*(float*)dst = *(float*)src;
}
int rcp_float_type_compair(void *src, void *dst){
	//this implement cause over flow
	//return *(float*)dst - *(float*)src;
	if (*(float*)dst<*(float*)src)
		return -1;
	if (*(float*)dst>*(float*)src)
		return +1;
	return 0;
}
struct rcp_type_core rcp_float_type = {
	sizeof(float),
	NULL,//init
	NULL,//free
	rcp_float_type_copy,
	rcp_float_type_compair,
};

void rcp_pointer_type_copy(void *src, void *dst){
	*(void**)dst = *(void**)src;
}
int rcp_pointer_type_compair(void *src, void *dst){
	//this implement cause over flow
	//return *(void**)dst - *(void**)src;
	if (*(void**)dst<*(void**)src)
		return -1;
	if (*(void**)dst>*(void**)src)
		return +1;
	return 0;
}
struct rcp_type_core rcp_pointer_type = {
	sizeof(void*),
	NULL,//init
	NULL,//free
	rcp_pointer_type_copy,
	rcp_pointer_type_compair,
};
