//This file was generated by program.

rcp_extern int rcp_uint8_type_compare(
		const void* ex, void* l, void* r);

rcp_extern int rcp_uint16_type_compare(
		const void* ex, void* l, void* r);

rcp_extern int rcp_uint32_type_compare(
		const void* ex, void* l, void* r);

rcp_extern int rcp_uint64_type_compare(
		const void* ex, void* l, void* r);

rcp_extern int rcp_int8_type_compare(
		const void* ex, void* l, void* r);

rcp_extern int rcp_int16_type_compare(
		const void* ex, void* l, void* r);

rcp_extern int rcp_int32_type_compare(
		const void* ex, void* l, void* r);

rcp_extern int rcp_int64_type_compare(
		const void* ex, void* l, void* r);

rcp_extern int rcp_float_type_compare(
		const void* ex, void* l, void* r);

rcp_extern int rcp_double_type_compare(
		const void* ex, void* l, void* r);

rcp_extern int rcp_pointer_type_compare(
		const void* ex, void* l, void* r);
