//This file was generated by program.

extern struct rcp_type_core rcp_type_uint64;

extern struct rcp_type_core rcp_type_uint32;

extern struct rcp_type_core rcp_type_uint16;

extern struct rcp_type_core rcp_type_uint8;

extern struct rcp_type_core rcp_type_int64;

extern struct rcp_type_core rcp_type_int32;

extern struct rcp_type_core rcp_type_int16;

extern struct rcp_type_core rcp_type_int8;

extern struct rcp_type_core rcp_type_double;

extern struct rcp_type_core rcp_type_float;

extern struct rcp_type_core rcp_type_pointer;
